# -*- coding: utf-8 -*-
"""Materiais.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Qxp6EAGWt-S6qEphtKRoKpTJsmLTh9v
"""

# GERADOR DE RELAÇÃO DE MATERIAIS (Ceminas)

import pandas as pd
import os

# Entrada do nome da OBRA
obra = input("Informe o nome da obra: ").strip()
if not obra:
    obra = "Sem_Nome"
obra_limpa = "".join(c for c in obra if c.isalnum() or c in (" ", "-", "_")).strip()

# Caminhos dos arquivos
base_dir = r"/content/drive/MyDrive/Materiais_Projeto"
arquivo_estruturas = os.path.join(base_dir, "MateriaisEstrutura.xlsx")
arquivo_projeto = os.path.join(base_dir, "EstruturasProjeto.xlsx")
arquivo_saida = os.path.join(base_dir, f"Ceminas - Materiais - {obra_limpa}.xlsx")

# Leitura das planilhas
estruturas = pd.read_excel(arquivo_estruturas, engine="openpyxl")
projeto = pd.read_excel(arquivo_projeto, engine="openpyxl")

# Padronização
for df in [estruturas, projeto]:
    df.columns = df.columns.str.strip().str.upper()
    for col in df.select_dtypes(include=["object"]).columns:
        df[col] = df[col].astype(str).str.strip().str.upper()

# Verificação de combinações ausentes
comb_keys = ["ESTRUTURA", "EQUIPAMENTO", "CONDUTOR", "POSTE"]

erros = pd.merge(
    projeto[comb_keys],
    estruturas[comb_keys],
    on=comb_keys,
    how="left",
    indicator=True
).query('_merge == "left_only"')[comb_keys].drop_duplicates()

if not erros.empty:
    print(f"\nForam encontradas {len(erros)} combinações inexistentes no banco de materiais.\n")
else:
    print("Todas as combinações do projeto estão cadastradas no banco.\n")

# Correção guiada

correcoes = {}
for _, linha in erros.iterrows():
    estrutura = linha["ESTRUTURA"]
    equipamento = linha["EQUIPAMENTO"]
    condutor = linha["CONDUTOR"]
    poste = linha["POSTE"]

    print(f"\nEstrutura não encontrada: {estrutura} | Equipamento: {equipamento} | Condutor: {condutor} | Poste: {poste}")

    # Sugestões disponíveis
    sugestoes = estruturas[estruturas["ESTRUTURA"] == estrutura][comb_keys].drop_duplicates()
    if sugestoes.empty:
        print("Nenhuma variação dessa estrutura existe no banco.")
        print("Essa linha será ignorada.")
        continue

    print("\nVariações disponíveis dessa estrutura:")
    for i, sug in sugestoes.iterrows():
        print(f"  [{i}]  {sug['EQUIPAMENTO']} | {sug['CONDUTOR']} | {sug['POSTE']}")

    escolha = input("Escolha o índice da combinação desejada ou pressione ENTER para ignorar: ").strip()

    if escolha.isdigit() and int(escolha) in sugestoes.index:
        nova = sugestoes.loc[int(escolha)].to_dict()
        correcoes[(estrutura, equipamento, condutor, poste)] = nova
        print(f"Substituição registrada: {nova}")
    else:
        print("Nenhuma substituição feita. Essa estrutura será ignorada.")

# Aplica as correções ao projeto
projeto_corrigido = projeto.copy()
for idx, row in projeto.iterrows():
    chave = (row["ESTRUTURA"], row["EQUIPAMENTO"], row["CONDUTOR"], row["POSTE"])
    if chave in correcoes:
        novo = correcoes[chave]
        projeto_corrigido.loc[idx, ["EQUIPAMENTO", "CONDUTOR", "POSTE"]] = [
            novo["EQUIPAMENTO"], novo["CONDUTOR"], novo["POSTE"]
        ]

# Geração da relação consolidada
materiais_lista = []

for _, row in projeto_corrigido.iterrows():
    filtro = (
        (estruturas["ESTRUTURA"] == row["ESTRUTURA"]) &
        (estruturas["EQUIPAMENTO"] == row["EQUIPAMENTO"]) &
        (estruturas["CONDUTOR"] == row["CONDUTOR"]) &
        (estruturas["POSTE"] == row["POSTE"])
    )

    encontrados = estruturas.loc[filtro].copy()
    if not encontrados.empty:
        encontrados["QTD_PROJETO"] = row["QUANTIDADE"]
        materiais_lista.append(encontrados)

if materiais_lista:
    materiais = pd.concat(materiais_lista, ignore_index=True)
    materiais["QTD_TOTAL"] = materiais["QUANTIDADE"] * materiais["QTD_PROJETO"]

    relacao = (
        materiais.groupby(["CODIGO", "DESCRIÇÃO", "UNIDADE"], as_index=False)["QTD_TOTAL"]
        .sum()
        .sort_values("DESCRIÇÃO")
    )

    relacao.to_excel(arquivo_saida, index=False)
    print(f"\n✅ Relação consolidada gerada com sucesso!")
    print(f"📁 Arquivo salvo como: {arquivo_saida}")
    print(f"📦 Total de itens distintos: {len(relacao)}")
else:
    print("\n❌ Nenhuma estrutura válida encontrada. Verifique as planilhas.")